# Generated by Django 5.1.1 on 2024-09-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_annonces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces',
            name='articles',
        ),
        migrations.AddField(
            model_name='annonces',
            name='titre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
