# Generated by Django 5.1.1 on 2024-09-09 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_annonces_articles_annonces_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='titre',
            field=models.CharField(blank=True, null=True),
        ),
    ]
