# Generated by Django 5.1.1 on 2024-09-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_specificité'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='enpromo',
            field=models.BooleanField(default=False),
        ),
    ]
