# Generated by Django 5.1.1 on 2024-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_enpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='prix_promo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
