# Generated by Django 5.1.1 on 2024-09-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_articles_prix_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='prix_promo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
