# Generated by Django 5.1.1 on 2024-09-11 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_panier_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespanier',
            name='panier',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.panier'),
        ),
    ]
