# Generated by Django 5.1.1 on 2024-09-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_panier_articles_alter_articlespanier_panier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespanier',
            name='panier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.panier'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='articles',
            field=models.ManyToManyField(through='articles.ArticlesPanier', to='articles.articles'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
