# Generated by Django 5.1.1 on 2024-09-11 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_alter_articlespanier_panier_alter_panier_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlespanier',
            name='panier',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.panier'),
        ),
    ]
