# Generated by Django 5.1.1 on 2024-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_achatarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatarticle',
            name='quantite',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
