# Generated by Django 5.1.1 on 2024-09-20 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_alter_achatarticle_quantite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achatarticle',
            name='articlesPanier',
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='adresse',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='numero',
            field=models.IntegerField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='statue',
            field=models.CharField(default='En attente'),
        ),
        migrations.AddField(
            model_name='achatarticle',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
