# Generated by Django 5.1.1 on 2024-09-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0023_remove_achatarticle_articlespanier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achatarticle',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
