# Generated by Django 5.1.1 on 2024-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='first_name',
            field=models.CharField(blank=True, default='Ibrahima Sory', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='last_name',
            field=models.CharField(blank=True, default='Bangoura', max_length=25, null=True),
        ),
    ]
