# Generated by Django 5.1.1 on 2024-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usershop_first_name_alter_usershop_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='adresse',
            field=models.CharField(blank=True, default='Dixinn', max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='phone',
            field=models.CharField(blank=True, default='623205705', max_length=9, null=True, unique=True),
        ),
    ]
