# Generated by Django 5.1.1 on 2024-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usershop_adresse_alter_usershop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershop',
            name='adresse',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='usershop',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
