# Generated by Django 5.1.1 on 2024-09-23 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usershop_adresse_alter_usershop_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usershop',
            name='username',
        ),
    ]
